### ISSUE TITLE
.env.local not initiating when not using lando

### ISSUE THREAD

**Issue by nikunp** [pantheon-systems/wordpress-composer-managed#107]
I am using valet for local development and as soon as I remove `&& 'lando' === $ENV['Pantheon_Environment']` from line 40  in application.php my local environment works

**Comment by jazzsequence** [comment]
`application.php` is a file that is yours to modify as needed and, because of the myriad ways that people configure their local dev environments, Lando is the only local dev environment we can support. Closing this ticket, as I don't think we're going to add support for other local dev environments other than Lando, but this is a good reference if anyone else has similar issues with non-Lando-based dev environments.
