### ISSUE TITLE
Clarity on using `composer upstream-require`

### ISSUE THREAD

**Issue by screid123** [pantheon-systems/wordpress-composer-managed#41]
I created a site using this upstream, and I would still like to use the "one-click update" from the Pantheon dashboard to apply upstream changes. I am confused on which composer command I should use to load/manage my site's plugins and themes. Is it best-practice to use the `composer upstream-require` and leave the root `composer.json` alone? The comments/docs are a little confusing around this, and seem to be written for using/hosting a custom upstream (maybe?) even though the README suggests using the Pantheon upstream.

For example, if I want to include the Yoast SEO plugin for my site, which command would i use to avoid conflicts when applying upstream updates?
```
composer require yoast/wordpress-seo
```
or
```
composer upstream-require yoast/wordpress-seo
```

When I try to use `composer upstream-require`, it tells me that I cannot use it without modifying the root `composer.json` (at least the `name` property), but I am concerned that this may cause conflicts when applying upstream changes via Dashboard. Is the purpose of the "upstream-configuration" to give the sites a separate `composer.json` to use to customize, or is that literally meant for hosting your own upstream and shouldn't be used when working on a site referencing the Pantheon upstream?

For that matter, shouldn't this upstream repo have its dependencies listed in the `upstream-configuration/composer.json` and leave the root `composer.json` with the minimal setup/scripts to reference the upstream config (which would include the `roots/wordpress` and other dependencies presumably managed by this upstream)?

**Comment by screid123** [comment]
For example, compare [this repo's upstream-configuration/composer.json](https://github.com/pantheon-systems/wordpress-composer-managed/blob/default/upstream-configuration/composer.json) to the [wordpress-project's upstream-config/composer.json](https://github.com/pantheon-upstreams/wordpress-project/blob/master/upstream-config/composer.json). It would seem that the dependencies in the root `composer.json` of this repo should be moved to the `upstream-configration/composer.json` based on how the other upstream is set up.

**Comment by greg-1-anderson** [comment]
The `upstream/configuraion/composer.json` file is for use by custom upstreams that are based on a Pantheon standard upstream, e.g. this one. Pantheon might put a dependency here, but only if it is required for operation of the site, *and* the end user will never have the option to change the required version of the dependency. All of the Pantheon-supplied requirements are currently placed in the root-level composer.json file so that the end-user has the option to adjust the required version if desired.

An individual site should never modify the contents of anything in the upstream configuration folder. This directory is reserved for the use of the upstream, so that additions may be made without the risk of causing merge conflicts with sites based on it.

**Comment by jazzsequence** [comment]
Tracked internally as BUGS-5505

**Comment by jazzsequence** [comment]
The `upstream-require` script has been moved to https://packagist.org/packages/pantheon-systems/upstream-management, and out of this Composer configuration, so closing this issue. `pantheon-systems/upstream-management` can be required explicitly for custom upstreams that require it and I believe we've updated all the relevant documentation that previously suggested using `composer upstream-require` over `composer require` but feel free to re-open if this is still an issue.
